### PR TITLE
Prevent Copying Schema on every Write + Read

### PR DESCRIPTION
**Pull request by deankarn**
## PR
This changes `GetSchemaDefinition` to NOT serialize the schema to a `string` and then immediately parse it back to a `schema` definition on every `Write` and every `Read`(scan) of data. 

Perhaps there's a reason that I'm not understanding but I could not determine any reason why this would be needed.

I do see there's another similar change that's been merged yet unreleased but this PR handles it at the lower `schema` level and will apply to both the `reader` and `writer` at the core of the copy.

Changes Benchmarked:
### BEFORE
```
goos: darwin
goarch: amd64
pkg: github.com/fraugster/parquet-go/floor
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkReadFile-12               83163             13852 ns/op            2153 B/op         79 allocs/op
BenchmarkWriteFile-12              21464             55469 ns/op           10280 B/op        250 allocs/op

= 18,028 writes/s
= 72,191 reads/s
```

### AFTER
```
goos: darwin
goarch: amd64
pkg: github.com/fraugster/parquet-go/floor
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkReadFile-12              681856              1534 ns/op             544 B/op         35 allocs/op
BenchmarkWriteFile-12             237277              4926 ns/op            4176 B/op         89 allocs/op

= 203,004 writes/s
= 651,890 reads/s
```

### CODE REVIEW

**Comment by deankarn** [comment]
Checking in to see if this PR needs anything else?

**Comment by deankarn** [comment]
Checking in again to see if anything else is needed?

**Comment by akrennmair** [comment]
Hi, sorry for not getting back to you earlier. IIRC, there was a specific reason why we implemented a deep copy of the `GetSchemaDefinition` method like that, but I can't remember it. I found the revision where this was changed, `c5d735c1`, and all it says is "fix the schema copy issue". Maybe @fzerorubigd remembers more about this?

**Comment by deankarn** [comment]
@akrennmair I can’t see a reason beyond the schema changing mid-flight.

either way let me know and if it is indeed required I can create a PR to make the deep copy more efficient.

**Comment by fzerorubigd** [comment]
There was a use case to create a copy of a parquet file with different schema, (adding or deleting a field) the problem was by modifying the target schema the original one was modified therefore we implemented the deep copy.

**Comment by deankarn** [comment]
@fzerorubigd this sounds like a special use case, copying a file, which makes sense but also a misuse of the same schema and not needed during normal operation; copying the schema on each read +write.

It seems this may have slipped into the normal operation because the function in question wasn’t clear on what it did.

I propose keeping the function in this PR returning the already parsed schema, as it’s named, and add a new function denoting a copy eg. Clone()

This way you can have the functionality for both use cases and it’s usage is clear.

let me know what you think :)

**Comment by akrennmair** [comment]
@deankarn that sounds like a sensible approach.

**Review by akrennmair — APPROVED** [review]
LGTM.

**Pull request merged**
